### ISSUE TITLE
dependency version with letters in it

### ISSUE THREAD

**Issue by gandulf** [ksoichiro/gradle-eclipse-aar-plugin#3]
Hi,
I just replaced some of my local jars, with the proper gradle dependencies and stumbled over another problems:

One of my jars must have a dependency with an library whose version has rc (release candidate)  in it's version. Then I get the following exception from your plugin:

```
Caused by: java.lang.NumberFormatException: For input string: "rc"
    at com.github.ksoichiro.eclipse.aar.GenerateTask$__clinit__closure1.doCall(GenerateTask.groovy:22)
    at com.github.ksoichiro.eclipse.aar.GenerateTask$_getLatestDependencies_closure12_closure54.doCall(GenerateTask.groovy:192)
    at com.github.ksoichiro.eclipse.aar.GenerateTask$_getLatestDependencies_closure12.doCall(GenerateTask.groovy:191)
    at com.github.ksoichiro.eclipse.aar.GenerateTask.getLatestDependencies(GenerateTask.groovy:185)
    at com.github.ksoichiro.eclipse.aar.GenerateTask$_exec_closure4.doCall(GenerateTask.groovy:114)
    at com.github.ksoichiro.eclipse.aar.GenerateTask.exec(GenerateTask.groovy:113)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
```

by the way great work. keep it up :-)

**Comment by gandulf** [comment]
I found out with dependency was messing up the plugin:
- com.bingzer.android.driven:driven-gdrive:1.0.0

it seems google itself has some weird versions:
- com.google.api-client » google-api-client-android    _1.18.0-rc_
- com.google.apis » google-api-services-drive  _v2-rev126-1.18.0-rc_

**Comment by ksoichiro** [comment]
Thanks for reporting! I'll fix it soon.

**Comment by ksoichiro** [comment]
I've fixed it. Could you please try again?

**Comment by gandulf** [comment]
No error is thrown an the dependencies are added. So looks fine.

**Comment by ksoichiro** [comment]
Thanks for checking!
